name: 'Setup, Build and Publish'
on:
  workflow_call:
    inputs:
      branch_name:
        type: string
        description: 'Branch name'
        required: true
      image_version:
        type: string
        description: 'Image version for docker hub'
        required: true
      cmake_options:
        type: string
        description: 'Additional cmake options'
        required: false
      build_type:
        type: string
        description: 'Build type of skaled binary'
        required: true
      node_type:
        type: string
        description: 'Node type of skaled build'
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    steps:  
      - name: Compose docker image name
        if: inputs.node_type != 'Historic'
        run: |
          [[ $BUILD_TYPE = "Debug" ]] && export VERSION_SUFFIX=debug || export VERSION_SUFFIX=release
          export VERSION=${{ github.event.inputs.image_version }}-$VERSION_SUFFIX
          echo "VERSION=$VERSION" >> $GITHUB_ENV
  
      - name: Compose docker image name (historic)
        if: inputs.node_type == 'Historic'
        run: |
          [[ $BUILD_TYPE = "Debug" ]] && export VERSION_SUFFIX=debug || export VERSION_SUFFIX=release
          export VERSION=${{ github.event.inputs.image_version }}-$VERSION_SUFFIX-historic
          echo "VERSION=$VERSION" >> $GITHUB_ENV
